FEEDBACK_CHANNELS = range(5, 15)
PAD_FEEDBACK_CHANNEL = FEEDBACK_CHANNELS[-1]
LOOP_FEEDBACK_CHANNEL = 0
NON_FEEDBACK_CHANNEL = 15
PAD_TRANSLATIONS = (
 (0, 0, 24, PAD_FEEDBACK_CHANNEL),
 (1, 0, 25, PAD_FEEDBACK_CHANNEL),
 (2, 0, 26, PAD_FEEDBACK_CHANNEL),
 (3, 0, 27, PAD_FEEDBACK_CHANNEL),
 (0, 1, 16, PAD_FEEDBACK_CHANNEL),
 (1, 1, 17, PAD_FEEDBACK_CHANNEL),
 (2, 1, 18, PAD_FEEDBACK_CHANNEL),
 (3, 1, 19, PAD_FEEDBACK_CHANNEL),
 (0, 2, 8, PAD_FEEDBACK_CHANNEL),
 (1, 2, 9, PAD_FEEDBACK_CHANNEL),
 (2, 2, 10, PAD_FEEDBACK_CHANNEL),
 (3, 2, 11, PAD_FEEDBACK_CHANNEL),
 (0, 3, 0, PAD_FEEDBACK_CHANNEL),
 (1, 3, 1, PAD_FEEDBACK_CHANNEL),
 (2, 3, 2, PAD_FEEDBACK_CHANNEL),
 (3, 3, 3, PAD_FEEDBACK_CHANNEL))
PLAYHEAD_FEEDBACK_CHANNELS = range(1, 9)
